# Generated by Django 3.0.2 on 2020-02-12 17:04

import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Фото для баннера',
                'verbose_name_plural': 'Фото для баннера',
            },
        ),
        migrations.CreateModel(
            name='ContactsSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('en_title', models.TextField(blank=True, max_length=300, null=True, verbose_name='EN--->title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('en_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
                ('en_keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='ContactsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', ckeditor.fields.RichTextField(max_length=6000, verbose_name='Текст')),
                ('en_sub1', ckeditor.fields.RichTextField(blank=True, max_length=6000, null=True, verbose_name='EN--->Текст')),
            ],
            options={
                'verbose_name': 'Текст на стр Контакты',
                'verbose_name_plural': 'Текст на стр Контакты',
            },
        ),
    ]
