# Generated by Django 3.0.2 on 2020-02-12 17:03

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seotitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Seo-title')),
                ('seodescript', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Seo-description')),
                ('seokeywords', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Seo-keywords')),
                ('title', models.CharField(max_length=400, verbose_name='Название статьи')),
                ('slug', models.SlugField(unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для оформления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип материала(статья/новость)',
                'verbose_name_plural': 'Тип материала(статья/новость)',
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='NewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seotitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Seo-title')),
                ('seodescript', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Seo-description')),
                ('seokeywords', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Seo-keywords')),
                ('slug', models.SlugField(unique=True)),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Обложка статьи/новости')),
                ('title', models.CharField(max_length=1000, verbose_name='Название статьи/новости')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст статьи/новости')),
                ('author', models.BooleanField(default=False, verbose_name='Авторская статья/новость')),
                ('origin_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название источника заимствования')),
                ('origin_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на источник заимствования')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время публикации')),
                ('order', models.FloatField(blank=True, null=True, verbose_name='Порядок группировки')),
                ('post', models.BooleanField(default=False, verbose_name='Опубликовано в авто режиме')),
                ('post_custom', models.BooleanField(default=False, verbose_name='Задержать публикацию')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCategory', verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Статья/Новость',
                'verbose_name_plural': 'Статьи/Новости',
            },
        ),
    ]
