# Generated by Django 3.0.3 on 2020-06-18 15:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlesseo_newsseo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesseo',
            options={'verbose_name': 'SEO | СТАТЬИ', 'verbose_name_plural': 'SEO | СТАТЬИ'},
        ),
        migrations.AlterModelOptions(
            name='newsseo',
            options={'verbose_name': 'SEO | НОВОСТИ', 'verbose_name_plural': 'SEO | НОВОСТИ'},
        ),
        migrations.AddField(
            model_name='newarticle',
            name='title_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст в афише статьи'),
        ),
    ]
