# Generated by Django 3.0.3 on 2020-07-03 14:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200618_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterModelOptions(
            name='articlesseo',
            options={'verbose_name': 'SEO ДЛЯ РАЗДЕЛА "СТАТЬИ"', 'verbose_name_plural': 'SEO ДЛЯ РАЗДЕЛА "СТАТЬИ"'},
        ),
        migrations.AlterModelOptions(
            name='newarticle',
            options={'verbose_name': 'СТАТЬЯ | НОВОСТЬ', 'verbose_name_plural': 'СТАТЬИ | НОВОСТИ'},
        ),
        migrations.AlterModelOptions(
            name='newsseo',
            options={'verbose_name': 'SEO ДЛЯ РАЗДЕЛА "НОВОСТИ"', 'verbose_name_plural': 'SEO ДЛЯ РАЗДЕЛА "НОВОСТИ"'},
        ),
        migrations.AddField(
            model_name='articlesseo',
            name='op_graph_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='ФОТО ДЛЯ OPENGRAPH'),
        ),
        migrations.AddField(
            model_name='newsseo',
            name='op_graph_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='ФОТО ДЛЯ OPENGRAPH'),
        ),
    ]
