# Generated by Django 3.0.2 on 2020-02-12 17:04

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('en_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->Текст')),
            ],
            options={
                'verbose_name': 'Блок преимущества',
                'verbose_name_plural': 'Блоки преимущества',
            },
        ),
        migrations.CreateModel(
            name='FooterContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', ckeditor_uploader.fields.RichTextUploadingField(max_length=4000, verbose_name='Текст контактов')),
                ('en_block', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4000, null=True, verbose_name='EN--->Текст контактов')),
            ],
            options={
                'verbose_name': 'Текст контактов в футере',
                'verbose_name_plural': 'Текст контактов в футере',
            },
        ),
        migrations.CreateModel(
            name='FooterPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для нижнего слайдера(992px)')),
                ('photo768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для нижнего слайдера(768px)')),
                ('photo576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для нижнего слайдера(576px)')),
            ],
            options={
                'verbose_name': 'Фото для нижнего слайдера',
                'verbose_name_plural': 'Фото для нижнего слайдера',
            },
        ),
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для главного слайдера(992px)')),
                ('photo768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для главного слайдера(768px)')),
                ('photo576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для главного слайдера(576px)')),
            ],
            options={
                'verbose_name': 'Фото для главной карусели',
                'verbose_name_plural': 'Фото для главной карусели',
            },
        ),
        migrations.CreateModel(
            name='MainPhotoEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для главного слайдера')),
                ('photo768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для главного слайдера(768px)')),
                ('photo576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для главного слайдера(576px)')),
            ],
            options={
                'verbose_name': 'Фото для главной карусели-->англ.версия',
                'verbose_name_plural': 'Фото для главной карусели-->англ.версия',
            },
        ),
        migrations.CreateModel(
            name='MainSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('en_title', models.TextField(blank=True, max_length=300, null=True, verbose_name='EN--->title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('en_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
                ('en_keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок')),
                ('en_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='EN--->Заголовок')),
                ('sub1', ckeditor_uploader.fields.RichTextUploadingField(max_length=6000, verbose_name='Текст в правой колонке')),
                ('en_sub1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='EN--->Текст в правой колонке')),
                ('sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в левой колонке')),
                ('en_sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='EN--->Текст в левой колонке')),
                ('sub1_turbo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Турбо-страницы | Первый абзац')),
                ('sub2_turbo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Турбо-страницы | Второй абзац')),
                ('sub1_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='AMP-страницы|Первый абзац')),
                ('sub2_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='AMP-страницы|Второй абзац')),
            ],
            options={
                'verbose_name': 'Основной текст',
                'verbose_name_plural': 'Основной текст',
            },
        ),
        migrations.CreateModel(
            name='MPBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для баннера(992px)')),
                ('photo768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для баннера(768px)')),
                ('photo576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для баннера(576px)')),
            ],
            options={
                'verbose_name': 'Фото для баннера',
                'verbose_name_plural': 'Фото для баннера',
            },
        ),
        migrations.CreateModel(
            name='MPBannerEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для баннера')),
            ],
            options={
                'verbose_name': 'Фото для баннера англ.версия',
                'verbose_name_plural': 'Фото для баннера англ.версия',
            },
        ),
    ]
