# Generated by Django 3.0.2 on 2020-02-12 18:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageText_P1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок')),
                ('en_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='EN--->Заголовок')),
                ('sub1', ckeditor_uploader.fields.RichTextUploadingField(max_length=6000, verbose_name='Текст в правой колонке')),
                ('en_sub1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='EN--->Текст в правой колонке')),
                ('sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в левой колонке')),
                ('en_sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='EN--->Текст в левой колонке')),
            ],
            options={
                'verbose_name': 'О компании(часть 1)',
                'verbose_name_plural': 'О компании(часть 1)',
            },
        ),
    ]
