# Generated by Django 3.0.2 on 2020-02-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainpagetext_p2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagetext_p2',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='mainpagetext_p2',
            name='title',
        ),
    ]
