# Generated by Django 3.0.2 on 2020-02-12 19:45

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200212_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTextBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для баннерв - 992px')),
                ('photo768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для баннерв - 768px')),
                ('photo576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для баннерв - 576px')),
            ],
            options={
                'verbose_name': 'Баннер раздела "О КОМПАНИИ"',
                'verbose_name_plural': 'Баннер раздела "О КОМПАНИИ"',
            },
        ),
    ]
