# Generated by Django 3.0.3 on 2020-02-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_maintextbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на страницк'),
        ),
    ]
