# Generated by Django 3.0.3 on 2020-06-30 13:28

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_advantage_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterContacts',
        ),
        migrations.DeleteModel(
            name='MainPhotoEn',
        ),
        migrations.DeleteModel(
            name='MainText',
        ),
        migrations.DeleteModel(
            name='MainTextBanner',
        ),
        migrations.DeleteModel(
            name='MPBanner',
        ),
        migrations.DeleteModel(
            name='MPBannerEN',
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'ПРЕИМУЩЕСТВА | БЛОК', 'verbose_name_plural': 'ПРЕИМУЩЕСТВА | БЛОКИ'},
        ),
        migrations.AlterModelOptions(
            name='mainpagetext_p1',
            options={'verbose_name': 'О КОМПАНИИ | ТЕКСТ | ЧАСТЬ 1', 'verbose_name_plural': 'О КОМПАНИИ | ТЕКСТ | ЧАСТЬ 1'},
        ),
        migrations.AlterModelOptions(
            name='mainpagetext_p2',
            options={'verbose_name': 'О КОМПАНИИ | ТЕКСТ | ЧАСТЬ 2', 'verbose_name_plural': 'О КОМПАНИИ | ТЕКСТ | ЧАСТЬ 2'},
        ),
        migrations.AlterModelOptions(
            name='mainphoto',
            options={'verbose_name': 'ГЛАВНЫЙ СЛАЙДЕР | ФОТО', 'verbose_name_plural': 'ГЛАВНЫЙ СЛАЙДЕР | ФОТО'},
        ),
        migrations.AlterModelOptions(
            name='mainseo',
            options={'verbose_name': 'SEO ДЛЯ ГЛАВНОЙ СТРАНИЦЫ', 'verbose_name_plural': 'SEO ДЛЯ ГЛАВНОЙ СТРАНИЦЫ'},
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_576_jp2',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 576х'),
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_576_webp',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | WEBP | 576х'),
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_768_jp2',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 768х'),
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_768_webp',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | WEBP | 768х'),
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_jp2',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 1920х500'),
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='photo_webp',
            field=models.CharField(blank=True, editable=False, max_length=600, null=True, verbose_name='ФОТО | WEBP | 1920х500'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='ФОТО | JPEG | 1920х500'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo768',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='ФОТО | JPEG | 768х'),
        ),
    ]
