# Generated by Django 3.0.3 on 2020-06-30 14:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200630_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(blank=True, max_length=6000, null=True, verbose_name='Фраза для слайдера')),
                ('en_sentence', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='EN--->Фраза для слайдера')),
            ],
            options={
                'verbose_name': 'ТЕКСТОВЫЙ СЛАЙДЕР',
                'verbose_name_plural': 'ТЕКСТОВЫЙ СЛАЙДЕР',
            },
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_576_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 576х'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_576_webp',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | WEBP | 576х'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_768_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 768х'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_768_webp',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | WEBP | 768х'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | JPEG 2000 | 1920х500'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='photo_webp',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ФОТО | WEBP | 1920х500'),
        ),
    ]
