# Generated by Django 3.0.3 on 2020-06-30 16:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200630_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainseo',
            options={'verbose_name': 'SEO | OPENGRAPH ДЛЯ ГЛАВНОЙ СТРАНИЦЫ', 'verbose_name_plural': 'SEO | OPENGRAPH ДЛЯ ГЛАВНОЙ СТРАНИЦЫ'},
        ),
        migrations.AddField(
            model_name='mainseo',
            name='op_graph_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='ФОТО ДЛЯ OPENGRAPH'),
        ),
    ]
