# Generated by Django 3.0.2 on 2020-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('en_title', models.TextField(blank=True, max_length=300, null=True, verbose_name='EN--->title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('en_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
                ('en_keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='EN--->keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
