# Generated by Django 3.0.3 on 2020-06-24 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metall',
            name='wiki_seo_descript',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='metall',
            name='wiki_seo_keywords',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='metall',
            name='wiki_seo_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
    ]
