# Generated by Django 3.0.2 on 2020-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, verbose_name='ID пользователя')),
                ('f_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя пользователя')),
                ('l_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фамилия пользователя')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано ли сообщение')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Url аватара')),
                ('title', models.CharField(max_length=1000, verbose_name='Тема сообщения')),
                ('date', models.TextField(max_length=6000, verbose_name='Дата сообщения')),
                ('body', models.TextField(max_length=6000, verbose_name='Дата сообщения')),
                ('idmes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID сообщения')),
                ('post', models.BooleanField(default=False, verbose_name='Отослано ли письмо?')),
            ],
            options={
                'verbose_name': 'Личное сообщение VK',
                'verbose_name_plural': 'Личные сообщения VK',
            },
        ),
        migrations.CreateModel(
            name='VKMessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, verbose_name='ID пользователя')),
                ('f_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя пользователя')),
                ('l_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фамилия пользователя')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано ли сообщение')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Url аватара')),
                ('title', models.CharField(max_length=1000, verbose_name='Тема сообщения')),
                ('date', models.TextField(max_length=6000, verbose_name='Дата сообщения')),
                ('body', models.TextField(max_length=6000, verbose_name='Дата сообщения')),
                ('idmes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID сообщения')),
                ('post', models.BooleanField(default=False, verbose_name='Отослано ли письмо?')),
            ],
            options={
                'verbose_name': 'Групповое сообщение VK',
                'verbose_name_plural': 'Групповые сообщения VK',
            },
        ),
    ]
