# Generated by Django 3.0.2 on 2020-02-12 17:02

import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Фото для баннера',
                'verbose_name_plural': 'Фото для баннера',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Фото для слайдера')),
            ],
            options={
                'verbose_name': 'Фото для слайдера на стр. Анализ металла',
                'verbose_name_plural': 'Фото для слайдера на стр. Анализ металла',
            },
        ),
        migrations.CreateModel(
            name='AnalysisSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', ckeditor.fields.RichTextField(max_length=6000, verbose_name='Абзац1')),
                ('sub2', ckeditor.fields.RichTextField(max_length=6000, verbose_name='Абзац2')),
            ],
            options={
                'verbose_name': 'Текст на стр Анализ металла',
                'verbose_name_plural': 'Текста на стр Анализ металла',
            },
        ),
    ]
