# Generated by Django 3.0.3 on 2020-07-02 18:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisphoto',
            options={'verbose_name': 'СЛАЙДЕР | ФОТО', 'verbose_name_plural': 'СЛАЙДЕР | ФОТО'},
        ),
        migrations.AlterModelOptions(
            name='analysisseo',
            options={'verbose_name': 'SEO ДЛЯ РАЗДЕЛА "АНАЛИЗ"', 'verbose_name_plural': 'SEO ДЛЯ РАЗДЕЛА "АНАЛИЗ"'},
        ),
        migrations.AlterModelOptions(
            name='textanalysis',
            options={'verbose_name': 'ТЕКСТ РАЗДЕЛА', 'verbose_name_plural': 'ТЕКСТ РАЗДЕЛА'},
        ),
        migrations.AddField(
            model_name='analysisseo',
            name='op_graph_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='ФОТО ДЛЯ OPENGRAPH'),
        ),
        migrations.AlterField(
            model_name='analysisphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
