# Generated by Django 3.0.2 on 2020-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModAppMess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=600, null=True, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Почта')),
                ('message', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
